### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="屏幕截图_20221209_202952.png"
Content-Type: application/octet-stream

< D:\Computers\Pictures\Screenshots\屏幕截图_20221209_202952.png
